routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');


// Documento
Route::get('documento/grid_ajax', 'DocumentoController@grid_ajax');
Route::delete('documento/destroyAll', 'DocumentoController@destroyAll');
Route::resource('documento', 'DocumentoController');

app/Documento.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Documento extends BaseModel
{
	protected $table = 'documento';
	protected $primaryKey = 'id_documento';
	protected $fillable = ['descricao', 'sigla'];
	
	// 
	public function getRules() {
		return [
				$this->getClassName() . '.descricao' => 'required',		
				$this->getClassName() . '.sigla' => 'required',		
			];
	}
	
	// 
	public $label = [
		'descricao' => 'Descrição',
		'sigla' 	=> 'Sigla',
	];
}

app/Http/Controllers/DocumentoController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
//use Illuminate\Support\Facades\Redirect;
//use Session;
//use App\Documento;

class DocumentoController extends BaseController
{
	public $title = 'Documento';
	public $modelName = 'Documento';
	public $modelPath = '\App\Documento';
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {		
		return parent::index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		return parent::create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		return parent::store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return parent::show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
		return parent::edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {		
		return parent::update($request, $id);
    }	

    /**
     * Remove the selected resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroyAll()
    {
		return parent::destroyAll();
    }	
	
	// 
	public function grid_ajax() {
		$columns = [
			'id_documento',
			'descricao',
			'sigla',
		];	
		
		$orderType 	= $_GET['order'][0]['dir'];		
		$page 		= ($_GET['start'] / $_GET['length']) + 1;
		$search 	= $_GET['search']['value'];		
		$orderKey   = $_GET['order'][0]['column'];
		$orderField = $columns[$orderKey];
		
		$model = DB::table( $this->modelName );
		$recordsTotal = $model->count();

		foreach($columns as $column) {
			$modelsCondition = $model->orWhere( $column, 'like', "%$search%" );
		}
        
        $recordsFiltered = $modelsCondition->count();
		
		$models = $modelsCondition->orderBy($orderField, $orderType)->forPage( $page, $_GET['length'] )->get();
		
		$modelData = [];		
		foreach($models->toArray() as $data) {
			$newData = [];
			foreach($columns as $column)
				$newData[$column] = $data->$column;		
			
            $modelData[] = $newData;
		}
		
		$data = array(
					'draw' => $_GET['draw'],
					"recordsTotal" => $recordsTotal,
					"recordsFiltered" => $recordsFiltered,
					'data' => $modelData,
				);

		echo json_encode($data);
	}
}

resources/views/documento/create.blade.php
<?php
use App\View\View;

$view = new View( ['controller' => $controller, 'errors' => $errors] );
?>

@extends('layouts.app')

@section('content')	
	<? $view->getHeader(); ?>
	
	<?= Form::formBegin( ['action' => route('documento.store')] ) ?>
		{{ csrf_field() }}
		
		<?= Form::htmlInput( ['type' => 'money', 'name' => 'Documento[descricao]', 'value' => old('Documento.descricao'), 'htmlOptions' => ['id' => 'documento-descricao'], 'label' => ['content' => $model->getLabel('descricao')], 'errors' => ($errors->has('Documento.descricao')) ] ) ?>
		<?= Form::htmlInput( ['type' => 'text', 'name' => 'Documento[sigla]', 'label' => ['content' => $model->getLabel('sigla')], 'errors' => ($errors->has('Documento.sigla')) ] ) ?>
		
        <?= Form::formButtons( ['baseUrl' => $controller->getControllerUri()] ) ?>
	<?= Form::formEnd() ?>	
@endsection

@section('js')
	$( document ).ready(function() {
		<?= Form::$outputJs; ?>
	});
@endsection	

resources/views/documento/edit.blade.php
<?php
use App\View\View;

$view = new View( ['controller' => $controller, 'errors' => $errors] );
?>

@extends('layouts.app')

@section('content')
	<? $view->getHeader(); ?>
	
	<?= Form::formBegin( ['action' => route( $controller->getControllerUri() . '.update', ['id'=> $model->id_documento])] ) ?>
		{{ csrf_field() }}
		<input type='hidden' name='_method' value='PUT'>        
        
		<?= Form::htmlInput( ['type' => 'text', 'name' => 'Documento[descricao]', 'value' => old('Documento.descricao', $model->descricao), 'htmlOptions' => ['id' => 'documento-descricao'], 'label' => ['content' => $model->getLabel('descricao')], 'errors' => ($errors->has('Documento.descricao')) ] ) ?>
		<?= Form::htmlInput( ['type' => 'text', 'name' => 'Documento[sigla]', 'value' => old('Documento.sigla', $model->sigla), 'htmlOptions' => ['id' => 'documento-sigla'], 'label' => ['content' => $model->getLabel('sigla')], 'errors' => ($errors->has('Documento.sigla')) ] ) ?>
        
		<?= Form::formButtons( ['baseUrl' => $controller->getControllerUri()] ) ?>
	<?= Form::formEnd() ?>	
@endsection

@section('js')
	$( document ).ready(function() {
		<?= Form::$outputJs; ?>
	});
@endsection	

resources/views/documento/index.blade.php
@extends('layouts.app')

@section('content')
	<?= Form::htmlTitle( ['content'=> $controller->title] ) ?>

	<?
	$config = array(
				'label' => $model->label,
				//'data' => $data,
				
				// optional parameter
				'menu' => [
					['label' => 'Item 1', 'href' => 'item1'],
					['label' => 'Item 2', 'href' => 'item2'],
				],
				'htmlTable' => array(
					'id' => 'example',						
				),
			);		
	$grid = new Grid($config);				
	echo $grid->init();
	?>		
@endsection

@section('js')
	$( document ).ready(function() {
		config = {
			'id': '<?= $grid->id ?>', 
			'baseUrl': '<?= url( $controller->getControllerUri() . '/') ?>',
			'ajaxUrl': '<?= url( $controller->getControllerUri() . '/grid_ajax/') ?>',
			'columns': [
				{ "data": "id_documento" },
				{ "data": "descricao" },
				{ "data": "sigla" },
			],
			'order': {
				'column': 1,
				'type': 'desc'
			}
		}
		
		grid(config);
	});
@endsection	

resources/views/documento/show.blade.php
<?php
use App\View\View;

$view = new View( ['controller' => $controller, 'errors' => $errors] );
?>

@extends('layouts.app')

@section('content')

	<? $view->getHeader(); ?>

	<table class="table table-striped">
		<?
		foreach($model->label as $key => $value) {
			echo "
				<tr>
					<td width='30%'>". $model->getLabel($key) ."</td>
					<td width='70%'>". $model->$key ."</td>
				</tr>
			";
		}		
		?>
	</table>

	<?= Form::backButton( ['baseUrl' => $controller->getControllerUri()] ) ?>
@endsection

@section('js')
	$( document ).ready(function() {
		<?= Form::$outputJs; ?>
	});
@endsection	